destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/framework-pdf"
port: 4010
output: pdf
product: framework
print_title: GUARDIAN - framework
print_subtitle: version X
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
